((nil . ((indent-tabs-mode . nil)
         (fill-column . 90)
         (compile-command . "dune build")
         (projectile-project-compilation-cmd . "dune build")
         (projectile-project-test-cmd . "dune runtest")))
 (caml-mode . ((tab-width . 2)))
 (ocaml-ts-mode . ((tab-width . 2)))
 (tuareg-mode . ((tab-width . 2)
                 (tuareg-indent-align-with-first-arg . t)
                 (tuareg-match-patterns-aligned . t))))
